version: "3.6"
services:
  httputil:
    image: golang:1.14-alpine
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      REDIS_URL: redis
      REDIS_PORT: 6379
      DB_DSN: pgsql:host=postgres;dbname=httputil
      DB_SERVER: pgsql
      DB_NAME: httputil
      DB_USER: httputil
      DB_PASSWORD: somepassword
      DB_PORT: 5432
    volumes:
      - .:/go/src/github.com/jasonmccallister/httputil
    working_dir: /go/src/github.com/jasonmccallister/httputil
    command: go run main.go
  redis:
    image: redis:5-alpine
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: SuperPassword123456!
      POSTGRES_DB: httputil
      POSTGRES_USER: httputil
      POSTGRES_PASSWORD: somepassword
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: httputil
      # So you don't have to use root, but you can if you like
      MYSQL_USER: httputil
      # You can use whatever password you like
      MYSQL_PASSWORD: somepassword
      # Password for root access
      MYSQL_ROOT_PASSWORD: somepassword
